---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo
  labels:
    app: todo
spec:
  serviceName: todo
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: pvc-todo-vol
          persistentVolumeClaim:
            claimName: pvc-todo
      initContainers:
        - name: chown-data
          image: "{{ .Values.image }}"
          command: [ "/bin/sh", "-c", "chown -R daemon /app/data" ]
          volumeMounts:
            - mountPath: "{{ .Values.dataDir }}"
              name: pvc-todo-vol
      containers:
        - name: todo
          image: "{{ .Values.image }}"
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: SECRET_KEY
            - name: PASSWORD_SALT
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: PASSWORD_SALT
            - name: ALLOW_NEW_ACCOUNTS
              value: "{{ .Values.allowNewAccounts }}"
            - name: DATABASE_PATH
              value: "{{ .Values.dataDir }}/todo.db"
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "{{ .Values.dataDir }}"
              name: pvc-todo-vol
