---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-todo
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: pd.csi.storage.gke.io
    fsType: ext4
    volumeHandle: {{ .Values.disk }}
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-todo
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-rwo
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-todo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
