from src.config import MIGRATIONS

SECRET_KEY = "test"
PASSWORD_SALT = "test"
ALLOW_NEW_ACCOUNTS = True
DATABASE_PATH = ":memory:"
DATABASE_MUTEX_TIMEOUT = 5

SESSION_COOKIE_HTTPONLY = True
REMEMBER_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
REMEMBER_COOKIE_SECURE = True
SESSION_COOKIE_NAME = "__todoapp"
SESSION_TYPE = "filesystem"
SESSION_USE_SIGNER = True
