---
name: test-after-push
run-name: Test Changes by ${{ github.actor }}
on: [ push ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - run: pytest
