---
name: "Test & Build"
run-name: Test Changes by ${{ github.actor }}
on:
  push:
    branches:
      - main
env:
  CR_PAT: ${{ secrets.CONTAINER_REGISTRY_KEY }}
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: lint
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: test
        if: ${{ success() }}
        run: |
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      - name: build
        if: ${{ success() }}
        run: |
          echo ${CR_PAT} | docker login ghcr.io -u henryroyal --password-stdin
          docker build -t todo:${TAG}
          docker push ghcr.io/henryroyal/todo:${{ vars.GITHUB_RUN_NUMBER }}
          docker inspect ghcr.io/henryroyal/todo:${{ vars.GITHUB_RUN_NUMBER }}
