---
name: "Test & Build"
run-name: Test Changes by ${{ github.actor }}
on:
  push:
    branches:
      - main
env:
  TAG: ${{ vars.GITHUB_RUN_NUMBER }}
  CR_PAT: ${{ secrets.CONTAINER_REGISTRY_KEY }}
jobs:
  setup:
    - name: Setup
      uses: actions/checkout@v3
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
  lint:
    steps:
      - name: Flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  test_and_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11", "3.12" ]
    steps:
      - name: Unit Tests
        run: pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      - name: Unit Tests
        run: |
          echo ${CR_PAT} | docker login ghcr.io -u henryroyal --password-stdin
          docker build -t todo:${TAG}
          docker push ghcr.io/henryroyal/todo:${TAG}
          docker inspect ghcr.io/henryroyal/todo:${TAG}
